// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBcjqV5W1ybj2ZP9N28giD2H7LfD6W478',
    appId: '1:1027101274168:web:a32afbbbeefd7ca5e576cd',
    messagingSenderId: '1027101274168',
    projectId: 'chat-app-6c828',
    authDomain: 'chat-app-6c828.firebaseapp.com',
    storageBucket: 'chat-app-6c828.appspot.com',
    measurementId: 'G-9VPGBRKTXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9UkiOikUh_gA6W47QK0_DkfLG6XKas24',
    appId: '1:1027101274168:android:c1ef30240fc7bccee576cd',
    messagingSenderId: '1027101274168',
    projectId: 'chat-app-6c828',
    storageBucket: 'chat-app-6c828.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCANrCds8TuVsRrhFnI9HRWkkrAhb5ZegM',
    appId: '1:1027101274168:ios:d18f1a7bc1ea94e4e576cd',
    messagingSenderId: '1027101274168',
    projectId: 'chat-app-6c828',
    storageBucket: 'chat-app-6c828.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCANrCds8TuVsRrhFnI9HRWkkrAhb5ZegM',
    appId: '1:1027101274168:ios:acbe9703076f42d8e576cd',
    messagingSenderId: '1027101274168',
    projectId: 'chat-app-6c828',
    storageBucket: 'chat-app-6c828.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
